@baseUrl = http://localhost:6688

### signup user
POST {{baseUrl}}/api/signup
Content-Type: application/json

{
    "workspace": "test",
    "fullname": "startdusk",
    "email": "startdusk@acme.org",
    "password": "password"
}

### signup user ben
POST {{baseUrl}}/api/signup
Content-Type: application/json

{
    "workspace": "test",
    "fullname": "ben",
    "email": "ben@acme.org",
    "password": "password"
}

### signin user(valid)
# @name signin
POST {{baseUrl}}/api/signin
Content-Type: application/json

{
    "email": "startdusk@acme.org",
    "password": "password"
}

###
@authToken = {{signin.response.body.$.token}}

### signin user(invalid)
POST {{baseUrl}}/api/signin
Content-Type: application/json

{
    "email": "unknown@acme.org",
    "password": "password"
}

### get chat list
GET {{baseUrl}}/api/chat
Authorization: Bearer {{authToken}}

### get user list
GET {{baseUrl}}/api/users
Authorization: Bearer {{authToken}}
