### signup user
POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "fullname": "startdusk",
    "email": "startdusk@acme.org",
    "password": "password"
}

### signin user(valid)
POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "startdusk@acme.org",
    "password": "password"
}

### signin user(invalid)
POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "unknown@acme.org",
    "password": "password"
}
