@baseUrl = http://localhost:6688

### signup user
POST {{baseUrl}}/api/signup
Content-Type: application/json

{
    "workspace": "test",
    "fullname": "user",
    "email": "user@acme.org",
    "password": "password"
}

### signup user ben
POST {{baseUrl}}/api/signup
Content-Type: application/json

{
    "workspace": "test",
    "fullname": "ben",
    "email": "ben@acme.org",
    "password": "password"
}

### signin user(valid)
# @name signin
POST {{baseUrl}}/api/signin
Content-Type: application/json

{
    "email": "startdusk@acme.org",
    "password": "password"
}

###
@authToken = {{signin.response.body.$.token}}

### signin user(invalid)
POST {{baseUrl}}/api/signin
Content-Type: application/json

{
    "email": "unknown@acme.org",
    "password": "password"
}

### get chat list
GET {{baseUrl}}/api/chats
Authorization: Bearer {{authToken}}

### create chat
POST {{baseUrl}}/api/chats
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "name": "acme",
    "members": [1,2],
    "public": false
}



### get user list
GET {{baseUrl}}/api/users
Authorization: Bearer {{authToken}}

### upload files
POST {{baseUrl}}/api/upload
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="file"; filename="leetcode.png"
Content-Type: application/octet-stream

< leetcode.png
--MyBoundary
Content-Disposition: form-data; filename="hello.txt"
Content-Type: text/plain

Hello, World!
--MyBoundary--

### get files txt
GET {{baseUrl}}/api/files/1/0a0/a9f/2a6772942557ab5355d76af442f8f65e01.txt
Authorization: Bearer {{authToken}}

### get files png
GET {{baseUrl}}/api/files/1/1f5/80b/372d457f616afdc8d24f969966deb6dc17.png
Authorization: Bearer {{authToken}}
